#!/usr/bin/env Rscript

# Plot ROC curve from ROC coordinates generated by train_model.py.
#
# Usage:
# Rscript scripts/plot_roc_curve.R results/liver_internal_roc.csv results/liver_internal_roc.pdf "#F6B956" "Liver metastasis ROC"

args <- commandArgs(trailingOnly = TRUE)

if (length(args) < 4) {
  stop("Usage: Rscript plot_roc_curve.R <roc_csv> <output_pdf> <color> <title>")
}

roc_file <- args[1]
output_pdf <- args[2]
curve_color <- args[3]
plot_title <- args[4]

library(ggplot2)
library(dplyr)
library(readr)

roc_df <- read_csv(roc_file, show_col_types = FALSE)

if (!all(c("fpr", "sensitivity") %in% colnames(roc_df))) {
  stop("ROC file must contain columns: fpr and sensitivity")
}

auc_area_df <- roc_df %>%
  transmute(x = fpr, y = sensitivity) %>%
  arrange(x) %>%
  add_row(x = 0, y = 0, .before = 1) %>%
  add_row(x = 1, y = 0, .after = nrow(.))

p <- ggplot(roc_df, aes(x = fpr, y = sensitivity)) +
  geom_polygon(
    data = auc_area_df,
    aes(x = x, y = y),
    fill = curve_color,
    alpha = 0.30,
    inherit.aes = FALSE
  ) +
  geom_line(color = curve_color, linewidth = 1.2) +
  geom_segment(
    aes(x = 0, xend = 1, y = 0, yend = 1),
    color = "grey50",
    linetype = "dashed"
  ) +
  labs(
    title = plot_title,
    x = "False positive rate (1 - specificity)",
    y = "True positive rate (sensitivity)"
  ) +
  theme_classic() +
  theme(
    plot.title = element_text(hjust = 0.5, size = 14, face = "bold"),
    axis.title = element_text(size = 12, face = "bold"),
    axis.text = element_text(size = 10, color = "black"),
    panel.border = element_rect(colour = "black", fill = NA, linewidth = 0.8)
  )

ggsave(output_pdf, p, width = 4.5, height = 4.0)

message("Saved ROC plot to ", output_pdf)
